// api de usuario em objeto {}
const usuarioBruno = {
    "login": "bchavs12",
    "id": 100075447,
    "node_id": "U_kgDOBfcHtw",
    "avatar_url": "https://avatars.githubusercontent.com/u/100075447?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bchavs12",
    "html_url": "https://github.com/bchavs12",
    "followers_url": "https://api.github.com/users/bchavs12/followers",
    "following_url": "https://api.github.com/users/bchavs12/following{/other_user}",
    "gists_url": "https://api.github.com/users/bchavs12/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bchavs12/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bchavs12/subscriptions",
    "organizations_url": "https://api.github.com/users/bchavs12/orgs",
    "repos_url": "https://api.github.com/users/bchavs12/repos",
    "events_url": "https://api.github.com/users/bchavs12/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bchavs12/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Bruno Chaves",
    "company": "https://bchavs12.github.io/Portfolio/",
    "blog": "https://www.linkedin.com/in/bchavs12/",
    "location": "Porto Alegre - Rio Grande Do Sul",
    "email": null,
    "hireable": null,
    "bio": "💻 Desenvolvedor Web FullStack.\r\n⚡Em processo de desenvolvimento profissional.\r\n",
    "twitter_username": null,
    "public_repos": 12,
    "public_gists": 0,
    "followers": 6,
    "following": 14,
    "created_at": "2022-02-20T12:33:56Z",
    "updated_at": "2022-08-14T06:05:26Z"
}
  
console.log(usuarioBruno.avatar_url);